version: '3'
services:
  timesketch:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    links:
      - elasticsearch
      - postgres
      - redis
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_PORT=5432
      - ELASTIC_ADDRESS=elasticsearch
      - ELASTIC_PORT=9200
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - NEO4J_ADDRESS=neo4j
      - NEO4J_PORT=7474
    restart: always

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - ../contrib/add_label.groovy:/usr/share/elasticsearch/config/scripts/add_label.groovy
      - ../contrib/toggle_label.groovy:/usr/share/elasticsearch/config/scripts/toggle_label.groovy
      - /usr/share/data/elasticsearch:/var/lib/elasticsearch

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - /var/lib/postgres:/var/lib/postgres

  redis:
    image: redis:3

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    restart: always
